### ISSUE TITLE
Support to encode image.RGBA?

### ISSUE THREAD

**Issue by lming** [pixiv/go-libjpeg#19]
It seems right now jpeg.Encode() can only take image.Gray and image.YCBCr.
Is it possible to support image.RGBA? I have images generated by image/draw, which cannot be image.YCBCr.

**Comment by codeskyblue** [comment]
I found some write convert YCBCr to RGBA function. maybe can be some help: <https://github.com/disintegration/imaging/blob/master/helpers.go#L320>

**Comment by harukasan** [comment]
Fixed in #33.
