### ISSUE TITLE
Memory safety

### ISSUE THREAD

**Issue by thinxer** [pixiv/go-libjpeg#21]
The garbage collector in newer Go (e.g. 1.5) got smarter. `jerr` sometimes gets collected and we crash.

Here: https://github.com/pixiv/go-libjpeg/blob/a79c3a8f1d88709bc1e79de4a37dadcfc36dd62d/jpeg/decompress.go#L77
and here: https://github.com/pixiv/go-libjpeg/blob/a79c3a8f1d88709bc1e79de4a37dadcfc36dd62d/jpeg/compress.go#L57

It is possible the source/dest managers will have similar issues. I've added some ugly code to keep `jerr` and `mgr` referenced and the crashes went away.

Some related issues:
+ https://github.com/golang/go/issues/11345
+ https://github.com/golang/go/issues/10303

**Comment by edvakf** [comment]
I see. go-thumber does it better (but uglier).

https://github.com/pixiv/go-thumber/blob/master/jpeg/jpeg_read.go#L155-L177

I'm trying to fix it cleanly, if I can. Any idea?

**Comment by edvakf** [comment]
https://github.com/pixiv/go-libjpeg/pull/22 This probably solves.

**Comment by thinxer** [comment]
The `mgr` made by `makeDestinationManager` may still be garbage collected.

In the meanwhile, It is okay to have a Go struct allocated on the C heap. However, variables reference by that struct will not be scanned by Go GC. In this case, the `r` variable is not referenced in Go anymore. I'm not sure if Go will garbage collect it.

**Comment by edvakf** [comment]
Really? `makeDestinationManager` returns the `mgr` and accessed later by `defer releaseDestinationManager(dstManager)`, so it doesn't look like a problem to me.

**Comment by thinxer** [comment]
@edvakf sorry I missed the commits following e801a2.

**Comment by edvakf** [comment]
Cool

**Comment by thinxer** [comment]
https://github.com/golang/proposal/blob/master/design/12416-cgo-pointers.md

We cannot assign io.Reader/io.Writer to a C struct in Go 1.6.

**Comment by harukasan** [comment]
See #25.

**Comment by harukasan** [comment]
#25 is merged.
