### ISSUE TITLE
go-libjpeg error jpeglib.h not found

### ISSUE THREAD

**Issue by g-rock84** [pixiv/go-libjpeg#43]
When I run the following I get this error:
`jerald$ go get github.com/pixiv/go-libjpeg/jpeg`
`go/src/github.com/pixiv/go-libjpeg/jpeg/compress.go:6:10: fatal error: 'jpeglib.h' file not found`
`#include "jpeglib.h"`

Any advice?

Edit: Never mind. It was an oversight on my part. I just ran `brew install jpeg` and the issue was fixed.

**Comment by harukasan** [comment]
Yes, go-libjpeg needs libjpeg.
