### ISSUE TITLE
install error jpeglib.h

### ISSUE THREAD

**Issue by Dunuin** [pixiv/go-libjpeg#49]
Tried to install it to my Raspberry Pi 3B with Raspbian Stretch and Go 1.10.1 but got this error:

```
pi@BM-Raspi-Server:~ $ go get github.com/barnacs/compy
# github.com/pixiv/go-libjpeg/jpeg
go/src/github.com/pixiv/go-libjpeg/jpeg/compress.go:6:21: fatal error: jpeglib.h: No such file or directory
 #include "jpeglib.h"
                     ^
compilation terminated.
```

How can I fix it?

**Comment by scaszoo** [comment]
@Dunuin 
you marked the issue as closed so it's probably solved. But as a hint for others looking for an answer:
'sudo apt-get install libjpeg-dev' should solve the issue :-)
